<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Our Services</name>
   <tag></tag>
   <elementGuidId>4782c6a2-ec22-4737-83bb-c87527f973a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comp-j6gqwjnf2label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-j6gqwjnf2label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7861923b-39ab-4eec-aa3e-e75d50151352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1zyfI</value>
      <webElementGuid>f7a9e40b-3807-4930-adc5-beeca40aa9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-j6gqwjnf2label</value>
      <webElementGuid>5bd9736c-832d-4d55-b127-57cbd991f848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our Services</value>
      <webElementGuid>a97326b9-c0c4-4d8b-ba89-50b3426528bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-j6gqwjnf2label&quot;)</value>
      <webElementGuid>f31bb3a4-940b-4a6b-a3f9-bed7593584cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-j6gqwjnf2label']</value>
      <webElementGuid>c09f94f8-0502-4eec-81c8-f241a7f5472c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-j6gqwjnf2']/a/div/div/p</value>
      <webElementGuid>54d64f9e-f3da-47df-b02c-5214d9800303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Choose Aptsoft Solutions?'])[1]/preceding::p[5]</value>
      <webElementGuid>a9b1b7cd-966f-4dc9-bc9b-7a3e26ec87fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkPlace21'])[1]/preceding::p[8]</value>
      <webElementGuid>4c9dac10-fa3a-4bd0-b297-919f4382978b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Our Services']/parent::*</value>
      <webElementGuid>447d83ea-0b51-4cd0-9cea-0edba5613f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/div/p</value>
      <webElementGuid>e21902c0-71df-478e-ba89-3c1346bee10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-j6gqwjnf2label' and (text() = 'Our Services' or . = 'Our Services')]</value>
      <webElementGuid>15efb9c9-bb19-439f-9f0c-ab8afdf7f1b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
