<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Contact Us</name>
   <tag></tag>
   <elementGuidId>648da602-706b-4ea8-b4fc-633900506c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comp-j6gqwjnf4label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-j6gqwjnf4label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>513f7525-a6e6-4fdf-af79-612913c4e083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1zyfI</value>
      <webElementGuid>84c970d0-d650-425c-b2ea-376bca694daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-j6gqwjnf4label</value>
      <webElementGuid>14597b65-8956-45cb-8661-f8c6e586dcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>0956e231-3bbb-4923-9b8a-44bed7b3b090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-j6gqwjnf4label&quot;)</value>
      <webElementGuid>6457910f-3812-44b6-af79-7910f2d32730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-j6gqwjnf4label']</value>
      <webElementGuid>a46b04eb-c678-41ec-a436-6fd2accf3f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-j6gqwjnf4']/a/div/div/p</value>
      <webElementGuid>953b6507-6ed4-418f-ae8d-2fef625ef371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appropriate Software Solutions'])[1]/preceding::p[3]</value>
      <webElementGuid>e917c8ff-c806-4a8e-8a85-42031dc9a626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unobtrusive, robust and detailed software solutions that are truly useful.'])[1]/preceding::p[3]</value>
      <webElementGuid>0a0a3d7d-94da-40c6-bdbe-4fc1f04af724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact Us']/parent::*</value>
      <webElementGuid>20a32313-588e-4d83-89b5-21dd2100d6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/div/div/p</value>
      <webElementGuid>7dd7f7d1-81d7-4539-bb34-520c5f432da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-j6gqwjnf4label' and (text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>a780f1da-74fc-4e03-93d2-bccc93f6fe93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
