<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Why Choose Us</name>
   <tag></tag>
   <elementGuidId>92a48475-c0f4-4674-83e3-7b4cf20281e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comp-j6gqwjnf1label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-j6gqwjnf1label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>65dca125-3a21-43d1-a73b-19e0609b764d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1zyfI</value>
      <webElementGuid>77d915d7-a91a-4d87-9470-8071132ed25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-j6gqwjnf1label</value>
      <webElementGuid>4181d628-a575-4906-968e-7ca4b048208f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Why Choose Us</value>
      <webElementGuid>482752c6-174d-48d8-b43f-44289d94061b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-j6gqwjnf1label&quot;)</value>
      <webElementGuid>b05e8f6d-84ae-4a02-9716-de140ec672b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-j6gqwjnf1label']</value>
      <webElementGuid>928d6af7-b2de-435d-8f02-8fca864cbd2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-j6gqwjnf1']/a/div/div/p</value>
      <webElementGuid>17354687-d0b7-4766-b166-e0212d1ad796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appropriate Software Solutions'])[1]/preceding::p[6]</value>
      <webElementGuid>60bcb9f0-daa7-472a-99af-0b3830421741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unobtrusive, robust and detailed software solutions that are truly useful.'])[1]/preceding::p[6]</value>
      <webElementGuid>190f1149-7de7-46ad-bd17-e74da55ea20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Why Choose Us']/parent::*</value>
      <webElementGuid>1229ddc0-dd84-459e-b5b7-d2b2c4fd7e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/div/p</value>
      <webElementGuid>d5ae29a1-b902-4d50-81db-ee96d6093ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-j6gqwjnf1label' and (text() = 'Why Choose Us' or . = 'Why Choose Us')]</value>
      <webElementGuid>2ed84eba-62d7-4202-9312-217c8e7faf62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
